package enel.dev.budgets.objects.category;

import enel.dev.budgets.R;


public class Icon {

    public static int[] icons() {
        return new int[]{
                R.drawable.icon_star,
                R.drawable.icon_aspiradora,
                R.drawable.icon_ayuntamiento,
                R.drawable.icon_balance,
                R.drawable.icon_baby,
                R.drawable.icon_baby2,
                R.drawable.icon_balanza,
                R.drawable.icon_ball,
                R.drawable.icon_beer,
                R.drawable.icon_bike,
                R.drawable.icon_birthday,
                R.drawable.icon_book,
                R.drawable.icon_box,
                R.drawable.icon_bus,
                R.drawable.icon_buy,
                R.drawable.icon_calculator,
                R.drawable.icon_camera,
                R.drawable.icon_car,
                R.drawable.icon_casino,
                R.drawable.icon_celebration,
                R.drawable.icon_cesta,
                R.drawable.icon_cheque,
                R.drawable.icon_chesse,
                R.drawable.icon_children,
                R.drawable.icon_christmas,
                R.drawable.icon_cigar,
                R.drawable.icon_cine,
                R.drawable.icon_clothes,
                R.drawable.icon_coffe,
                R.drawable.icon_coinchange,
                R.drawable.icon_coins,
                R.drawable.icon_cold,
                R.drawable.icon_crown,
                R.drawable.icon_cubiertos,
                R.drawable.icon_dance,
                R.drawable.icon_decoration,
                R.drawable.icon_diamond,
                R.drawable.icon_diente,
                R.drawable.icon_doctor,
                R.drawable.icon_donation,
                R.drawable.icon_electric,
                R.drawable.icon_estacionamiento,
                R.drawable.icon_estadio,
                R.drawable.icon_factura,
                R.drawable.icon_fire,
                R.drawable.icon_fly,
                R.drawable.icon_gas,
                R.drawable.icon_gasoline,
                R.drawable.icon_gift,
                R.drawable.icon_graduation,
                R.drawable.icon_gym,
                R.drawable.icon_hipoteca,
                R.drawable.icon_home,
                R.drawable.icon_hospital,
                R.drawable.icon_hospital2,
                R.drawable.icon_hospital3,
                R.drawable.icon_icecream,
                R.drawable.icon_iglesia,
                R.drawable.icon_interest,
                R.drawable.icon_jeringa,
                R.drawable.icon_joystick,
                R.drawable.icon_keys,
                R.drawable.icon_labial,
                R.drawable.icon_laptop,
                R.drawable.icon_lavadora,
                R.drawable.icon_lawyer,
                R.drawable.icon_love,
                R.drawable.icon_law,
                R.drawable.icon_love2,
                R.drawable.icon_man,
                R.drawable.icon_market,
                R.drawable.icon_marriage,
                R.drawable.icon_martillo,
                R.drawable.icon_medal,
                R.drawable.icon_metrics,
                R.drawable.icon_milk,
                R.drawable.icon_money,
                R.drawable.icon_motorbike,
                R.drawable.icon_museum,
                R.drawable.icon_music,
                R.drawable.icon_paper,
                R.drawable.icon_peaje,
                R.drawable.icon_pets,
                R.drawable.icon_pharmacy,
                R.drawable.icon_pill,
                R.drawable.icon_phone,
                R.drawable.icon_phone2,
                R.drawable.icon_pintura,
                R.drawable.icon_planta,
                R.drawable.icon_planta2,
                R.drawable.icon_planta3,
                R.drawable.icon_recibo,
                R.drawable.icon_recycle,
                R.drawable.icon_star,
                R.drawable.icon_saves,
                R.drawable.icon_security,
                R.drawable.icon_swim,
                R.drawable.icon_sync,
                R.drawable.icon_taladro,
                R.drawable.icon_tarjet,
                R.drawable.icon_taxi,
                R.drawable.icon_tenis,
                R.drawable.icon_ticket,
                R.drawable.icon_ticket2,
                R.drawable.icon_tijeras,
                R.drawable.icon_train,
                R.drawable.icon_transfer,
                R.drawable.icon_transfer2,
                R.drawable.icon_tree,
                R.drawable.icon_usb,
                R.drawable.icon_user,
                R.drawable.icon_vacations,
                R.drawable.icon_veterinary,
                R.drawable.icon_wallet,
                R.drawable.icon_watch,
                R.drawable.icon_web,
                R.drawable.icon_wifi,
                R.drawable.icon_woman,
                R.drawable.icon_zapato,
                R.drawable.icon_unknown
        };
    }

    public static int icon(final int id) {
        try {
            return icons()[id];
        } catch(Exception ignored) {
            return icons()[0];
        }
    }

}
